DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS INGREDIENTS;
DROP TABLE IF EXISTS RECIPE_INGREDIENTS;
DROP TABLE IF EXISTS INSTRUCTIONS;

CREATE TABLE IF NOT EXISTS RECIPE
(
    ID             INTEGER UNIQUE NOT NULL PRIMARY KEY,
    NAME           VARCHAR(250)   NOT NULL,
    NO_OF_SERVINGS INTEGER        NOT NULL,
    VEG            CHAR(1)        NOT NULL,
    CRAT_TSP       TIMESTAMP      NOT NULL,
    CRAT_ID        VARCHAR(100)   NOT NULL, --IT SHOULD BE NUMERIC
    UPD_TSP        TIMESTAMP,
    UPD_ID         VARCHAR(100)             --IT SHOULD BE NUMERIC
);

CREATE TABLE IF NOT EXISTS INGREDIENTS
(
    ID       INTEGER UNIQUE NOT NULL PRIMARY KEY,
    NAME     VARCHAR(100)   NOT NULL,
    CRAT_TSP TIMESTAMP      NOT NULL,
    CRAT_ID  VARCHAR(100)   NOT NULL, --IT SHOULD BE NUMERIC
    UPD_TSP  TIMESTAMP,
    UPD_ID   VARCHAR(100)             --IT SHOULD BE NUMERIC
);

CREATE TABLE IF NOT EXISTS INSTRUCTIONS
(
    ID        INTEGER UNIQUE NOT NULL PRIMARY KEY,
    RECIPE_ID INTEGER,
    INS_STEPS VARCHAR(1024)  NOT NULL,
    CRAT_TSP  TIMESTAMP      NOT NULL,
    CRAT_ID   VARCHAR(100)   NOT NULL, --IT SHOULD BE NUMERIC
    UPD_TSP   TIMESTAMP,
    UPD_ID    VARCHAR(100)             --IT SHOULD BE NUMERIC
);

CREATE TABLE IF NOT EXISTS RECIPE_INGREDIENTS
(
    ID             INTEGER UNIQUE NOT NULL PRIMARY KEY,
    RECIPE_ID      INTEGER,
    INGREDIENTS_ID INTEGER
);

DROP SEQUENCE IF EXISTS RECIPE_SEQ;
DROP SEQUENCE IF EXISTS INGREDIENTS_SEQ;
DROP SEQUENCE IF EXISTS RECIPE_INGREDIENTS_SEQ;
DROP SEQUENCE IF EXISTS INSTRUCTIONS_SEQ;

CREATE SEQUENCE IF NOT EXISTS RECIPE_SEQ;
CREATE SEQUENCE IF NOT EXISTS INGREDIENTS_SEQ;
CREATE SEQUENCE IF NOT EXISTS RECIPE_INGREDIENTS_SEQ;
CREATE SEQUENCE IF NOT EXISTS INSTRUCTIONS_SEQ;